### ISSUE TITLE
Harness examples are not working via mock device on local machine

### ISSUE THREAD

**Issue by Aidar5** [CiscoTestAutomation/examples#54]
pyats run job demo1_harness_simple_job.py --testbed-file virl.yaml --replay mock_device
...
2022-06-14 14:22:45,237: %UNICON-INFO: +++ Unicon plugin iosxe (unicon.plugins.iosxe) +++
2022-06-14T14:22:45: %GENIE-ERROR: Traceback (most recent call last):
2022-06-14T14:22:45: %GENIE-ERROR:   File "src/genie/harness/_commons_internal.py", line 99, in genie.harness._commons_internal.connect.connection_task
2022-06-14T14:22:45: %GENIE-ERROR:   File "src/genie/harness/utils.py", line 309, in genie.harness.utils.connect_device
2022-06-14T14:22:45: %GENIE-ERROR:   File "src/genie/harness/utils.py", line 299, in genie.harness.utils.connect_device
2022-06-14T14:22:45: %GENIE-ERROR:   File "src/pyats/connections/manager.py", line 450, in pyats.connections.manager.ConnectionManager.connect
2022-06-14T14:22:45: %GENIE-ERROR:   File "src/pyats/connections/manager.py", line 419, in pyats.connections.manager.ConnectionManager.instantiate
2022-06-14T14:22:45: %GENIE-ERROR:   File "src/unicon/adapters/topology.py", line 575, in unicon.adapters.topology.Unicon
2022-06-14T14:22:45: %GENIE-ERROR:   File "src/unicon/playback/playback.py", line 48, in unicon.playback.playback.Playback.__init__
2022-06-14T14:22:45: %GENIE-ERROR: FileNotFoundError: [Errno 2] No such file or directory: 'mock_device/csr1000v-1'

**Comment by sjpatel21** [comment]
Hi,
I was able to run the example command successfully on my system. Based on the this error:
`FileNotFoundError: [Errno 2] No such file or directory: 'mock_device/csr1000v-1 
`  can you make sure that where you run this command, you have a directory `mock_device` and file named `csr1000v-1` inside it.

**Comment by Aidar5** [comment]
Hi,
I did fresh Debian11 install and got the same error. I think this is because there is simply no proper files in mock_devices folder provided for "harness" examples.  I used a command from Readme file.

root@debian:~/examples/libraries/harness_simple# pwd
/root/examples/libraries/harness_simple

root@debian:~/examples/libraries/harness_simple# ls mock_device/
**iosxe  nxos**

root@debian:~/examples/libraries/harness_simple# pyats run job demo1_harness_simple_job.py --testbed-file virl.yaml --replay mock_device
2022-06-19T15:34:11: %EASYPY-INFO: Starting job run: demo1_harness_simple_job

**Comment by sjpatel21** [comment]
Hello @Aidar5 
We are in the process of upgrading the documentation to support new features recently developed.
In the meanwhile, here is the workaround to let you continue testing.
This command should work:
`pyats run job demo1_harness_simple_job.py --testbed-file virl.yaml --disable-image-md5`

Please let me know if it works.
